services:
  postgres:
    image: postgres:15
    container_name: storeapi-postgres
    environment:
      POSTGRES_USER: storeapi_user
      POSTGRES_PASSWORD: storeapi_p@ssw0rd
      POSTGRES_DB: storeapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  storeapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=storeapi_db;Username=storeapi_user;Password=storeapi_p@ssw0rd
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
